/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xkgiydbjihgmctlidohn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZ2l5ZGJqaWhnbWN0bGlkb2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwOTg5NDksImV4cCI6MjA2OTY3NDk0OX0.ZxVjpaZxcIDk8gVoZwKfJ-M2-k2AXjZT6RFnDno-mEM"